create database customer_behavior;
use customer_behavior;

# what is total revenue generated by male vs female customers

select gender,sum(purchase_amount) as revenue
from customer_sales
group by gender;

# which customer used a discount but still spent more than the average purchase amount

select customer_id ,purchase_amount
from customer_sales
where discount_applied="Yes"and purchase_amount>(select avg(purchase_amount) from customer_sales);

# which are top 5 products with the highest average review rating
select item_purchased,round(avg(review_rating),2)as highest_review
from customer_sales
group by item_purchased
order by highest_review desc
limit 5 ;

# compare the average purchase amounts between standard and express shipping
select shipping_type,avg(purchase_amount) avg_shipping_amount
from customer_sales
where shipping_type in("Express","Standard")
group by shipping_type;

# Do subscribed customer spent more?compare average spend and total revenue between subscriber and non-subscribes
select subscription_status,count(customer_id) as total_customer,
sum(purchase_amount) as Total_revenue,
avg(purchase_amount) as avg_spend
from customer_sales
group by subscription_status
order by 1,2 desc;

# which 5 product have the highest percentage of purchases with discount applied
select item_purchased,
round(100* sum(case when discount_applied = "Yes" then 1 else 0 end )/count(*) ,2) as percentage
from customer_sales
group by item_purchased
order by percentage desc
limit 5;

# Segment customer into new ,returning and loyal based on their total number previous purchase,
#and show the count of each segment

select count(previous_purchases) as customer_count,
       case when previous_purchases =1 then "New"
       when previous_purchases between 2 and  10 then "Returning"
	else "Loyal"
	end as segment
from customer_sales
group by 2;

# what are the top 3 most purchased products within each category

with item_count as 
                  (select item_purchased,category,count(customer_id) as total_orders,
                  row_number() over (partition by category order by count(customer_id) desc) as item_rank
                  
from customer_sales
group by 1,2
)
select * from item_count
where item_rank <=3;

# Are customer who are repeat buyers(more than 5 previous purchases) also likly to subscribe

select subscription_status,count(customer_id) as repeat_buyers
from customer_sales
where previous_purchases > 5
group by subscription_status;

# what is revenue contribution of each age group 

select age_group,sum(purchase_amount) as revenue
from customer_sales
group by age_group
order by age_group;



